const router = require('express').Router();
const ctrl = require('../../controllers/apartment/unitController');
const auth = require('../../middleware/apartment/auth');
const sub = require('../../middleware/apartment/subscriptionCheck');
router.use(auth, sub);
router.get('/', ctrl.getAll);
router.get('/:id', ctrl.getById);
router.post('/', ctrl.create);
router.put('/:id', ctrl.update);
router.delete('/:id', ctrl.remove);
module.exports = router;