const router = require('express').Router();
const ctrl = require('../../controllers/cyber/computerController');
const auth = require('../../middleware/cyber/auth');
const sub = require('../../middleware/cyber/subscriptionCheck');
router.use(auth, sub);
router.get('/', ctrl.getAll);
router.post('/', ctrl.create);
router.put('/:id', ctrl.update);
router.delete('/:id', ctrl.remove);
module.exports = router;